### ISSUE TITLE
Adding the paper 'Collaboration-Aware Graph Convolutional Networks for Recommendation Systems'

### ISSUE THREAD

**Issue by yuwvandy** [mengliu1998/awesome-expressive-gnn#1]
Hi Meng,
 Thanks for creating such helpful repo for us focusing on graph expressivity. I recently have a paper on Arxiv, which leverages the collaboration of each neighborhood to determine their importance in passing their messages in recommendation systems. We theoretically prove that our designed CAGCN* can go beyond 1-WL in determining a 2nd order subgraph isomorphism specifically in the bipartite graph. Would you mind also adding this paper to this repo? Thank you so much!

 [arXiv 2022] Collaboration-Aware Graph Convolutional Networks for Recommendation Systems
 The link and code of the paper: https://arxiv.org/abs/2207.06221 and https://github.com/YuWVandy/CAGCN

Best,
Yu Wang

**Comment by mengliu1998** [comment]
Hi Yu,

This looks quite interesting and relevant. I will add it soon. Thank you.

**Comment by yuwvandy** [comment]
Hi Meng,
 Thank you!

Best,
Yu Wang

On Jul 18, 2022, at 9:16 PM, Meng Liu ***@***.******@***.***>> wrote:



Hi Yu,

This looks quite interesting and relevant. I will add it soon. Thank you.
